#+TITLE: Emacs Kit Org-mode
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:emacs-kit.org][Emacs Kit]].

* Emacs Kit Org
Configuration for the eminently useful [[http://orgmode.org/][Org Mode]].

Org-mode is for keeping notes, maintaining ToDo lists, doing project
planning, and authoring with a fast and effective plain-text system.
Org Mode can be used as a very simple folding outliner or as a complex
GTD system or tool for reproducible research and literate programming.

For more information on org-mode check out [[http://orgmode.org/worg/][worg]], a large Org-mode wiki
which is also *implemented using* Org-mode and [[http://git-scm.com/][git]].

* Loading stuff
  :PROPERTIES:
  :ID:       e3162d81-2e83-430f-b3b6-bca87ba2cc10
  :END:
#+begin_src emacs-lisp
  (add-to-list 'load-path (expand-file-name
                           "lisp" (expand-file-name
                                   "contrib" (expand-file-name
                                              "org" (expand-file-name
                                                     "elisp" dotfiles-dir)))))
  (require 'org-habit)
  (require 'org-id)
#+end_src

* Keybindings
  :PROPERTIES:
  :ID:       0c36320b-8323-46f2-be37-7ede76d19422
  :END:
#+begin_src emacs-lisp
  (global-set-key (kbd "C-c l") 'org-store-link)
  (global-set-key (kbd "<f12>") 'org-agenda)
  (global-set-key (kbd "C-c b") 'org-iswitchb)
    
  (global-set-key (kbd "<f9> i") 'bh/org-info)
    
  (global-set-key (kbd "<f9> I") 'org-clock-in)
  (global-set-key (kbd "<f9> O") 'org-clock-out)
  (global-set-key (kbd "<f9> J") 'org-clock-goto)
    
  (global-set-key (kbd "<f9> s") 'bh/switch-to-org-scratch)
  
#+end_src

* Auto mode and hooks
  :PROPERTIES:
  :ID:       f46b6f11-a9c5-492e-bac0-05ab170ea58f
  :END:
#+begin_src emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.\\(org\\|org_archive\\|txt\\)$" . org-mode))
  (add-hook 'org-mode-hook 'turn-on-auto-fill)
  (add-hook 'org-mode-hook 'turn-on-flyspell)
  (add-hook 'org-mode-hook 'turn-on-font-lock)
#+end_src

* Miscellaneous
  :PROPERTIES:
  :ID:       ccf92ab7-e9b5-4022-bb94-43fc6e47ab36
  :END:
#+begin_src emacs-lisp
  (setq org-startup-folded t)
  (setq org-cycle-separator-lines 0) ; leave no empty line in collapsed view
  (setq org-directory "~/.life-in-plain-text/")
  (setq org-default-notes-file (expand-file-name "refile.org" org-directory))
  (setq org-hide-leading-stars t)
  (setq org-odd-levels-only t)
  (setq org-popup-calendar-for-date-prompt nil)
  (setq org-return-follows-link t)
  (setq org-log-done 'time)
#+end_src


* List demote modify bullet
  :PROPERTIES:
  :ID:       98342890-a963-421a-bc47-8772fc17efe9
  :END:
  #+begin_src emacs-lisp
    (setq org-list-demote-modify-bullet
          '(("+" . "-") 
            ("-" . "+") 
            ("*" . "+")
            ("1." . "1)")
            ("1)" . "1.")))
  #+end_src
* Add final new line when saving files
  :PROPERTIES:
  :ID:       a0c886ce-4b7c-48cb-a8df-8821a5c61077
  :END:
#+begin_src emacs-lisp
  (setq require-final-newline t)
#+end_src 

* save all org buffers every hour
  :PROPERTIES:
  :ID:       7cdf7319-98c6-4f2f-bbf8-d694c87f4581
  :END:
#+begin_src emacs-lisp
  (run-at-time "00:59" 3600 'org-save-all-org-buffers)
#+end_src 

* TODO Stuff
  :PROPERTIES:
  :ID:       4811896b-c85e-4ffb-844f-1c30ab626d92
  :END:
#+begin_src emacs-lisp
  (setq org-todo-keywords 
        (quote (
                (sequence "TODO(t)" "NEXT(n!)" "|" "DONE(d!/!)")
                (sequence "WAITING(w!)" "SOMEDAY(S)" "|" "DELEGATED(D)" "CANCELLED(c@/!)")
                (sequence "TOREAD(o)" "FOUND(f)" "READING(r)" "|" "DONE(d!/!)" ))))
  
  
  (setq org-todo-keyword-faces 
        (quote (("TODO" :foreground "red" :weight bold)
                ("NEXT" :foreground "blue" :weight bold)
                ("DONE" :foreground "forest green" :weight bold)
                ("WAITING" :foreground "orange" :weight bold)
                ("SOMEDAY" :foreground "magenta" :weight bold)
                ("CANCELLED" :foreground "forest green" :weight bold))))
  
  (setq org-use-fast-todo-selection t)
  (setq org-treat-S-cursor-todo-selection-as-state-change nil)
#+end_src

* Agenda Stuff
*** agenda will always contain all TODO entries.
    :PROPERTIES:
    :ID:       070eab9f-b2d7-43e3-a4ff-5aadfaac927e
    :END:
    #+begin_src emacs-lisp
      (setq org-agenda-include-all-todo t)
    #+end_src 
*** don't show scheduled and deadline items when done
    :PROPERTIES:
    :ID:       a7986ac6-f292-4629-be88-f3116a1c5a84
    :END:
    #+begin_src emacs-lisp
      (setq org-agenda-skip-scheduled-if-done t
            org-agenda-skip-deadline-if-done t)
    #+end_src
*** do not include diary entries
    :PROPERTIES:
    :ID:       c3cba288-758c-4b5d-ac07-e143cfd4e843
    :END:
    #+begin_src emacs-lisp
      (setq org-agenda-include-diary nil)
    #+end_src
*** Number of days to include in overview display.
    :PROPERTIES:
    :ID:       9a362cdb-93da-4799-b74c-8fdaed1e375e
    :END:
    #+begin_src emacs-lisp
      (setq org-agenda-ndays 1)
    #+end_src
*** Custom Agenda Keys
    :PROPERTIES:
    :ID:       09a85bb4-e61d-4509-bc28-2ab821c4575c
    :END:
    #+begin_src emacs-lisp
      (setq org-agenda-custom-commands
            (quote (
                    ("r" "Refile New Notes and Tasks" tags "LEVEL=2+REFILE"
                     ((org-agenda-todo-ignore-with-date nil)
                      (org-agenda-todo-ignore-deadlines nil)
                      (org-agenda-todo-ignore-scheduled nil))))))
    #+end_src
*** Jump to org-agenda after Idle time.
    :PROPERTIES:
    :ID:       09c76154-42aa-4fb9-b6eb-1d2d311f0b42
    :END:
    #+begin_src emacs-lisp
      (defun jump-to-org-agenda ()
        (interactive)
        (let ((buf (get-buffer "*Org Agenda*"))
              wind)
          (if buf
              (if (setq wind (get-buffer-window buf))
                  (select-window wind)
                (if (called-interactively-p)
                    (progn
                      (select-window (display-buffer buf t t))
                      (org-fit-window-to-buffer)
                      ;; (org-agenda-redo)
                      )
                  (with-selected-window (display-buffer buf)
                    (org-fit-window-to-buffer)
                    ;; (org-agenda-redo)
                    )))
            (call-interactively 'org-agenda-list)))
        ;;(let ((buf (get-buffer "*Calendar*")))
        ;;  (unless (get-buffer-window buf)
        ;;    (org-agenda-goto-calendar)))
        )
      
      (run-with-idle-timer 900 t 'jump-to-org-agenda)
    #+end_src
*** Org agenda files
    :PROPERTIES:
    :ID:       b7ff7f3f-89c2-46f9-89b6-5708b07278a6
    :END:
    #+begin_src emacs-lisp
      (setq org-agenda-files (expand-file-name "agenda-files.org" org-directory))
    #+end_src 

*** Items to show in org-agenda-log-mode
#+begin_src emacs-lisp
  (setq org-agenda-log-mode-items '(clock))
#+end_src

*** Window settings for agenda
    #+begin_src emacs-lisp
      (setq org-agenda-restore-windows-after-quit t)
    #+end_src
* Reminders with appt
*** Erase all reminders; Rebuilt reminders for today agenda
    :PROPERTIES:
    :ID:       b4e41265-3530-4f44-b35e-0eec288dc17c
    :END:
    #+begin_src emacs-lisp
      (defun bh/org-agenda-to-appt ()
        (interactive)
        (setq appt-time-msg-list nil)
        (org-agenda-to-appt))
    #+end_src
      
*** Rebuild the reminders everytime the agenda is displayed
    :PROPERTIES:
    :ID:       2af03fa0-50e3-4307-b3a6-8217adc48da2
    :END:
    #+begin_src emacs-lisp
      (add-hook 'org-finalize-agenda-hook 'bh/org-agenda-to-appt)
    #+end_src      

*** Setup appointments
    :PROPERTIES:
    :ID:       993c6fdf-e03c-48f2-92e1-e76b9b480cd4
    :END:
    #+begin_src emacs-lisp
      (bh/org-agenda-to-appt)
      
      (appt-activate t)
      
      ;; (when window-system
        
      ;;   (setq appt-display-format 'window)
      
      ;;   (defun org-osd-display (min-to-app new-time msg)
      ;;     (save-window-excursion
      ;;       (shell-command (format "notify-send %s" msg))))
        
      ;;   (setq appt-disp-window-function (function org-osd-display))
        
      ;;   ;; Run once, activate and schedule refresh
      ;;   (run-at-time nil 3600 'bh/org-agenda-to-appt)
      ;;   (appt-activate t))
    #+end_src

*** reset the appointments one minute after midnight
    :PROPERTIES:
    :ID:       e069f013-f865-42da-9bc1-ba4e42a6f22f
    :END:
    #+begin_src emacs-lisp
      (run-at-time "24:01" nil 'bh/org-agenda-to-appt)
    #+end_src
* Refiling
*** from doc.norang
    :PROPERTIES:
    :ID:       0e352805-ff1a-45db-ba30-f14b0326c6f7
    :END:
  #+begin_src emacs-lisp
  ; Use IDO for target completion
  (setq org-completion-use-ido t)
  ; Targets include this file and any file contributing to the agenda - up to 5 levels deep
  (setq org-refile-targets (quote ((org-agenda-files :maxlevel . 5) (nil :maxlevel . 5))))
  ; Targets start with the file name - allows creating level 1 tasks
  (setq org-refile-use-outline-path (quote file))
  ; Targets complete in steps so we start with filename, TAB shows the next level of targets etc
  (setq org-outline-path-complete-in-steps t)
  ; Allow refile to create parent tasks with confirmation
  (setq org-refile-allow-creating-parent-nodes (quote confirm))
#+end_src
*** Refile to date-tree                            :emacs:orgmode:code:elisp:
    :PROPERTIES:
    :Post Date: [2010-07-30 Fri 05:33]
    :ID:       o2b-2b577bcd-5fb3-4841-b6d7-abd78ef713b3
    :CATEGORIES: ology
    :Post ID: 1027
    :END:
    Useful to refile notes to the journal file, which is a
    date-tree. =org-refile= isn't convenient to refile stuff to a
    date-tree. 
    #+begin_src emacs-lisp
      (defun my/org-refile-to-journal ()
        "Refile an entry to journal file's date-tree"
        (interactive)
        (require 'org-datetree)
        (let ((journal "journal.org")
              post-date)
          (setq post-date (or (org-entry-get (point) "TIMESTAMP_IA")
                              (org-entry-get (point) "TIMESTAMP")))
          (setq post-date (nthcdr 3 (parse-time-string post-date)))
          (setq post-date (list (cadr post-date) 
                                (car post-date) 
                                (caddr post-date)))
          (org-cut-subtree)
          (with-current-buffer (or (find-buffer-visiting journal)
                                   (find-file-noselect file))
            (save-excursion
              (org-datetree-file-entry-under (current-kill 0) post-date)
              (bookmark-set "org-refile-last-stored")))
          (message "Refiled to %s" journal)))
      
      (defun my/org-agenda-refile-to-journal ()
        "Refile the item at point to journal."
        (interactive)
        (let* ((marker (or (org-get-at-bol 'org-hd-marker)
                           (org-agenda-error)))
               (buffer (marker-buffer marker))
               (pos (marker-position marker)))
          (with-current-buffer buffer
            (save-excursion
              (save-restriction
                (widen)
                (goto-char marker)
                (org-remove-subtree-entries-from-agenda)
                (my/org-refile-to-journal)))))
        (org-agenda-redo))
      
      (org-defkey org-agenda-mode-map (kbd "C-c C-S-w") 'my/org-agenda-refile-to-journal)
      (org-defkey org-mode-map (kbd "C-c C-S-w") 'my/org-refile-to-journal)
    #+end_src
* Archiving
  :PROPERTIES:
  :ID:       ce71b551-3dca-42ec-a9ab-b448b11d52a1
  :END:
#+begin_src emacs-lisp
  ;; Donot change status of items when archiving.
  (setq org-archive-mark-done nil)
  ;;
#+end_src

* org-capture stuff
  :PROPERTIES:
  :ID:       cc6cae19-f085-485a-8086-78a2ce6732b9
  :END:
#+begin_src emacs-lisp
  (require 'org-capture)
  (global-set-key (kbd "C-M-r") 'org-capture)
  
  ;; org-protocol
  (require 'org-protocol)
  
  (setq org-capture-templates
        '(("a" "accounts" table-line
           (file+headline "accounts.org" "Expenses")
           "|%^{To/From}|%^{Detail}|%^{Amount}|%u|" :immediate-finish t)
          ("b" "book" entry
           (file+headline "books.org" "Book List")
           "%[template-books]" :immediate-finish t)
          ("c" "contacts" entry
           (file+headline "contacts.org" "Contacts")
           "%[template-contacts]" :immediate-finish t)
          ("l" "bLog" entry
           (file+headline "refile.org" "Notes")
           "* %^{Title} :ol:noexport:%^G \n  :PROPERTIES:\n  :POST_DATE: %U\n  :WEB_CAT: %^{Category} :END:\n\n  %?" :clock-in t :clock-resume t)
          ("n" "note" entry
           (file+headline "refile.org" "Notes")
           "* %^{About} :note:%^G \n\n  %U\n\n  %?" :clock-in t :clock-resume t)           
          ("t" "task" entry
           (file+headline "refile.org" "Tasks")
           "* TODO %? \n  " :clock-in t :clock-resume t)
          ("x" "org-protocol save relevant links" item
           (clock)
           "+ [[%:link][%:description]]" :immediate-finish t)
          ("w" "org-protocol bookmarks" entry
           (file+headline "refile.org" "Links")
           "* %:description %^G:\n  %u\n  %:link\n  %i" :immediate-finish t)))
    
  
#+end_src

* Clocking stuff
*** Misc
    :PROPERTIES:
    :ID:       073dabcb-36d6-46bc-811e-1a22c8408a00
    :END:
#+begin_src emacs-lisp
  ;; Resume clocking tasks when emacs is restarted
  (setq org-clock-persist 'history)
  (org-clock-persistence-insinuate)
  (setq org-clock-history-length 28)
  ;; Resume clocking task on clock-in if the clock is open
  (setq org-clock-in-resume t)
  ;; Change task state to STARTED when clocking in
  (setq org-clock-in-switch-to-state (quote bh/clock-in-to-next))
  ;;Resolving idle time
  (setq org-clock-idle-time 5)
  ;; Separate drawers for clocking and logs
  (setq org-drawers (quote ("PROPERTIES" "LOGBOOK" "CLOCK")))
  ;; Save clock data in the CLOCK drawer and state changes and notes in the LOGBOOK drawer
  (setq org-clock-into-drawer "CLOCK")
  ;; Sometimes I change tasks I'm clocking quickly - this removes clocked tasks with 0:00 duration
  (setq org-clock-out-remove-zero-time-clocks t)
  ;; Don't clock out when moving task to a done state
  (setq org-clock-out-when-done nil)
  ;; Disable auto clock resolution
  (setq org-clock-auto-clock-resolution nil)
  
#+end_src

*** Removing empty clock drawers on clock out
    :PROPERTIES:
    :ID:       dd338080-1a41-4a09-92e6-4db7b3297a30
    :END:
#+begin_src emacs-lisp
  (defun bh/remove-empty-drawer-on-clock-out ()
    (interactive)
    (save-excursion
      (beginning-of-line 0)
      (org-remove-empty-drawer-at "CLOCK" (point))))
  
  (add-hook 'org-clock-out-hook 'bh/remove-empty-drawer-on-clock-out 'append)
#+end_src

*** Change task state to NEXT from TODO when clocking in
    :PROPERTIES:
    :ID:       a152dabf-0db0-4593-9248-1bfa51f2f066
    :END:
  #+begin_src emacs-lisp
  (defun bh/clock-in-to-next (kw)
    "Switch task from TODO to NEXT when clocking in.
  Skips remember tasks and tasks with subtasks"
    (if (and (string-equal kw "TODO")
             (not (string-match "^CAPTURE.+org$"(buffer-name) )))
        (let ((subtree-end (save-excursion (org-end-of-subtree t)))
              (has-subtask nil))
          (save-excursion
            (forward-line 1)
            (while (and (not has-subtask)
                        (< (point) subtree-end)
                        (re-search-forward "^\*+ " subtree-end t))
              (when (member (org-get-todo-state) org-not-done-keywords)
                (setq has-subtask t))))
          (when (not has-subtask)
            "NEXT"))))
  #+end_src 
*** Effort Estimates
***** Column view headings
      :PROPERTIES:
      :ID:       15d7b402-c7aa-480b-a1cf-57644add06b5
      :END:
      #+begin_src emacs-lisp
        (setq org-columns-default-format "%80ITEM(Task) %10Effort(Effort){:} %10CLOCKSUM")
      #+end_src
***** Effort Estimate Global Values
      :PROPERTIES:
      :ID:       c0649f3b-9be3-4778-923d-1c330d61ba06
      :END:
      #+begin_src emacs-lisp
        (setq org-global-properties (quote (("Effort_ALL" . "0:10 0:30 1:00 2:00 3:00 4:00 5:00 6:00 7:00 8:00"))))
      #+end_src
* org-publish
  :PROPERTIES:
  :ID:       c35ae38c-8381-4570-81f8-d3bf583ea25c
  :END:
*** Blog Publish configuration
#+begin_src emacs-lisp
  (setq org-export-htmlize-output-type 'css)
  (require 'org-publish)
#+end_src
* org-export-generic
  :PROPERTIES:
  :ID:       684a27ca-692a-41eb-875e-5defd0301590
  :END:
#+begin_src emacs-lisp
(require 'org-export-generic)

;; Org to rst export 
(org-set-generic-type
 "restructured-text" 
 '(:file-suffix  ".rst"
   :key-binding  ?R

   :title-prefix              ?=
   :title-format              "%s\n"
   :title-suffix              ?=

   :body-header-section-numbers nil	; t = all, nil = none
   :body-section-header-format  "%s\n"
   :body-section-header-suffix  (?= ?- ?~ 
   				 ?+ ?^)
   :body-section-prefix         "\n"
   :body-section-suffix         "\n"

   :body-list-prefix             "<list>\n\n"
   :body-list-suffix             "</list>\n"
   :body-list-format             "+ %s\n"
   
   :body-number-list-prefix       "\n\n"
   :body-number-list-suffix       "\n"
   :body-number-list-format       "%s\n"
   :body-number-list-leave-number t

;;   :body-line-export-preformated t
;;   :body-line-fixed-prefix       "<pre>\n"
;;   :body-line-fixed-suffix       "\n</pre>\n"
;;   :body-line-fixed-format       "%s\n"

;;   :body-line-format             "%s"
;;   :body-line-wrap               60	; wrap at 60 chars

;;   :body-text-prefix 	       "<p>\n"
;;   :body-text-suffix 	       "</p>\n"
  
   ))

;; #+LaTeX_CLASS: beamer in org files
;; (unless (boundp 'org-export-latex-classes)
;;   (setq org-export-latex-classes nil))

;; (add-to-list 'org-export-latex-classes
;;   ;;beamer class, for presentations
;;   '("beamer"
;;      "\\documentclass[11pt]{beamer}\n
;;       \\mode<{{{beamermode}}}>\n
;;       \\usetheme{{{{beamertheme}}}}\n
;;       \\usecolortheme{{{{beamercolortheme}}}}\n
;;       \\setbeameroption{show notes}\n
;;       \\useoutertheme{infolines}\n
;;       \\setbeamercovered{transparent}\n
;;       \\useoutertheme{infolines}\n
;;       \\usepackage[utf8]{inputenc}\n
;;       \\usepackage[T1]{fontenc}\n
;;       \\usepackage{hyperref}\n
;;       \\usepackage{color}
;;       \\usepackage{listings}
;;       \\lstset{language=Python,
;;         basicstyle=\\ttfamily\\bfseries,
;;         commentstyle=\\color{red}\\itshape,
;;         stringstyle=\\color{darkgreen},
;;         showstringspaces=false,
;;         keywordstyle=\\color{blue}\\bfseries}\n
;;       \\usepackage{verbatim}\n
;;       \\institute{{{{beamerinstitute}}}}\n          
;;        \\subject{{{{beamersubject}}}}\n"

;;      ("\\section{%s}" . "\\section*{%s}")
     
;;      ("\\begin{frame}[fragile]\\frametitle{%s}"
;;        "\\end{frame}"
;;        "\\begin{frame}[fragile]\\frametitle{%s}"
;;        "\\end{frame}")))
#+end_src

* Org git documentation with info
  :PROPERTIES:
  :ID:       9d7426e7-1e2a-4b2f-9911-1e979583f8a1
  :END:
#+begin_src emacs-lisp
  (defun bh/org-info ()
    (interactive)
    (info "~/.emacs.d/elisp/org/doc/org.info"))
#+end_src
* Babel
*** Set languages
    :PROPERTIES:
    :ID:       ab78f0bc-301a-4456-914a-a5aef810ecb8
    :END:
    #+begin_src emacs-lisp
      (org-babel-do-load-languages
       'org-babel-load-languages
       '((python . t)
         (emacs-lisp . t)
         ))
    #+end_src
* org export with listings
  #+begin_src emacs-lisp
  (setq org-export-latex-listings t)
  #+end_src
* evaluating babel on exports
  #+begin_src emacs-lisp
    (unless (equal system-name "padma")
      (setq org-export-babel-evaluate nil))
  #+end_src
* Fix for YASnippet to work
  #+begin_src emacs-lisp
  (defun yas/org-very-safe-expand ()
    (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
  #+end_src

  #+begin_src emacs-lisp
  (add-hook 'org-mode-hook
            (lambda ()
              ;; yasnippet (using the new org-cycle hooks)
              (make-variable-buffer-local 'yas/trigger-key)
              (setq yas/trigger-key [tab])
              (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
              (define-key yas/keymap [tab] 'yas/next-field)
              ))
  #+end_src
* org-scratch buffer
  :PROPERTIES:
  :ID:       86f54e89-2ed4-4d0b-bfcd-36c4f247ade0
  :END:
#+begin_src emacs-lisp
  (defun bh/switch-to-org-scratch ()
    "Switch to a temp Org buffer.
    If the region is active, insert it."
    (interactive)
    (let ((contents
           (and (region-active-p)
                (buffer-substring (region-beginning)
                                  (region-end)))))
      (find-file "/tmp/org-scratch.org")
      (if contents (insert contents))))
#+end_src

